name: 'Setup Project'

description: 'Sets up the project in order to be usable for development'

outputs:
  fcg:
    description: "Python file in fcg/"
    value: ${{ steps.find-python-files.outputs.fcg }}
  scripts:
    description: "Python file in scripts/"
    value: ${{ steps.find-python-files.outputs.scripts }}
  tests:
    description: "Python file in tests/"
    value: ${{ steps.find-python-files.outputs.tests }}

runs:
  using: 'composite'

  steps:
    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    - name: 'Install dependencies'
      run: |
        sudo apt update
        sudo apt install -y mpich libopenmpi-dev libxml2-dev libxslt1-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: 'Install in develop mode'
      run: |
        pip install --editable .
      shell: bash

    - name: 'Find Python files in fcg/, scripts/ and tests/'
      id: find-python-files
      run: |
        echo "::set-output name=fcg::$(git ls-files 'fcg/**.py' | xargs echo)"
        echo "::set-output name=scripts::$(git ls-files 'scripts/**.py' | xargs echo)"
        echo "::set-output name=tests::$(git ls-files 'tests/**.py' | xargs echo)"
      shell: bash