name: 'CI'

on: [ push ]

jobs:
  clean_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'Setup the project'
        id: setup-project
        uses: ./.github/actions/setup-project

      - name: 'Format Python code with `brunette` and `black`'
        run: |
          brunette setup.py ${{ steps.setup-project.outputs.fcg }} ${{ steps.setup-project.outputs.scripts }} ${{ steps.setup-project.outputs.tests }}

      - name: 'Commit changes made by `brunette` and `black` formatters'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "`${{ github.workflow }}.${{ github.job }}`: Formatted Python code with `brunette` and `black`"

      - name: 'Sort Python imports with `isort`'
        run: |
          isort --jobs 0 setup.py ${{ steps.setup-project.outputs.fcg }} ${{ steps.setup-project.outputs.scripts }} ${{ steps.setup-project.outputs.tests }}

      - name: 'Commit changes made by `isort`'
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "`${{ github.workflow }}.${{ github.job }}`: Sorted Python code with `isort`"

  static_analysis:
    runs-on: ubuntu-latest
    needs: clean_code

    steps:
      - uses: actions/checkout@v3

      - name: 'Setup the project'
        id: setup-project
        uses: ./.github/actions/setup-project

      - name: 'Linting with `pylint`'
        run: |
          pylint --jobs 0 ${{ steps.setup-project.outputs.fcg }} ${{ steps.setup-project.outputs.scripts }}
          pylint --jobs 0 --disable=missing-docstring,protected-access ${{ steps.setup-project.outputs.tests }}
          pylint --disable=missing-docstring setup.py

      - name: 'Linting with `flake8`'
        run: |
          flake8 setup.py ${{ steps.setup-project.outputs.fcg }} ${{ steps.setup-project.outputs.scripts }} ${{ steps.setup-project.outputs.tests }}

      - name: 'Check static types with `mypy`'
        run: |
          mypy ${{ steps.setup-project.outputs.fcg }} ${{ steps.setup-project.outputs.scripts }} ${{ steps.setup-project.outputs.tests }}

      - name: 'Test with `pytest`'
        run: |
          pytest ${{ steps.setup-project.outputs.tests }}