name: Static analysis

on: [ push ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.8' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ SIMULATION_GENERATOR_PULL_GIT_SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements.txt

      - name: Find Python files in scripts/ and tests/
        id: find_python_files
        run: |
          echo "::set-output name=py_files::$(git ls-files 'scripts/*.py' 'tests/*.py')"

      - name: Linting with pylint
        run: |
          pylint ${{ steps.find_python_files.outputs.py_files }}

      - name: Linting with flake8
        # 120 max line length is taken from linumpy
        run: |
          flake8 --max-line-length=120 ${{ steps.find_python_files.outputs.py_files }}