name: Sync LINUM mirror repository

on:
  push:
    branches:
      - prod

jobs:
  sync_mirror_repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'prod'
          fetch-depth: 0

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://git@github.com:linum-uqam/inm5803-ete2022-benoit-dubreuil.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}